git-trim: switch to tag/revision checkout
```
    thread 'main' panicked at 'Unable to generate the cargo keys!: could not find repository from '/private/tmp/git-trim-20221223-41391-12z15g/git-trim-0.4.3'; class=Repository (6); code=NotFound (-3)', build.rs:5:31
```

Signed-off-by: Rui Chen <rui@chenrui.dev>